name: CI Master

on:
  push:
    branches:
      - master

jobs:
  CI-master-windows-x64:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          architecture: x64
      
      - name: Instalar dependências
        run: npm install --no-save
      
      - name: Pre Build node x64
        run: npm run prebuild:master -- --strip -t 18.20.6 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -a x64 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build Electron x64
        run: npm run prebuild:master -- --strip -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -r electron -a x64 -u ${{ secrets.GH_TOKEN }}

  CI-master-windows-ia32:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          architecture: x86
      
      - name: Instalar dependências
        run: npm install --no-save
      
      - name: Pre Build node ia32
        run: npm run prebuild:master -- --strip -t 18.20.6 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -a ia32 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build Electron ia32
        run: npm run prebuild:master -- --strip -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -r electron -a ia32 -u ${{ secrets.GH_TOKEN }}

  CI-master-ubuntu-x64:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install CUPS
        run: |
          sudo apt-get update
          sudo apt-get install -y libcups2-dev build-essential python-is-python3 gcc g++ make
      
      - name: Instalar dependências
        run: npm install --no-save
      
      - name: Pre Build node x64
        run: npm run prebuild:master -- --strip -t 18.20.6 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -a x64 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build Electron x64
        run: npm run prebuild:master -- --strip -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -r electron -a x64 -u ${{ secrets.GH_TOKEN }}

  CI-master-ubuntu-ia32:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install build dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            gcc-multilib \
            g++-multilib \
            libcups2-dev:i386 \
            build-essential \
            python3 \
            gcc \
            g++ \
            make \
            lib32z1
          sudo ln -sf /usr/bin/python3 /usr/bin/python
      
      - name: Setup environment for ia32
        run: |
          echo "CFLAGS=-m32" >> $GITHUB_ENV
          echo "CXXFLAGS=-m32" >> $GITHUB_ENV
          echo "LDFLAGS=-m32" >> $GITHUB_ENV
          echo "PYTHON=$(which python3)" >> $GITHUB_ENV
          echo "npm_config_arch=ia32" >> $GITHUB_ENV
          echo "npm_config_target_arch=ia32" >> $GITHUB_ENV
      
      - name: Instalar dependências
        env:
          CFLAGS: -m32
          CXXFLAGS: -m32
          LDFLAGS: -m32
        run: npm install --no-save
      
      - name: Pre Build node ia32
        env:
          CFLAGS: -m32
          CXXFLAGS: -m32
          LDFLAGS: -m32
        run: npm run prebuild:master -- --strip -t 18.20.6 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -a ia32 -u ${{ secrets.GH_TOKEN }}
      
      - name: Pre Build Electron ia32
        env:
          CFLAGS: -m32
          CXXFLAGS: -m32
          LDFLAGS: -m32
        run: npm run prebuild:master -- --strip -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0 -t 33.0.0 -t 34.0.0 -r electron -a ia32 -u ${{ secrets.GH_TOKEN }}